# Streamlit Cloud Secrets Configuration Template
# This file shows the structure needed for .streamlit/secrets.toml in Streamlit Cloud
# DO NOT commit actual secrets to the repository

# Required Environment Variables for Streamlit Cloud:
# 
# In your Streamlit Cloud app settings, add these secrets:
#
# OPENAI_API_KEY = "sk-your-actual-openai-api-key-here"
# STREAMLIT_ENV = "production"
# APP_NAME = "EzLipJob - LinkedIn Job Application Assistant"
# DEBUG_MODE = "false"
# MAX_FILE_SIZE_MB = "10"
# RATE_LIMIT_PER_HOUR = "100"
#
# Optional Advanced Settings:
# CUSTOM_PROMPT_PREFIX = "You are a professional career assistant..."
# COMPANY_RESEARCH_ENABLED = "true"
# DEFAULT_TONE = "professional"

# Example secrets.toml structure for Streamlit Cloud:
# [general]
# OPENAI_API_KEY = "sk-your-key-here"
# STREAMLIT_ENV = "production"